// Popup maskotunun rastgele baloncuk metinleri (humor + teknik ipuçları, TR/EN).
(function (global) {
  // Dil anahtarına göre maskot baloncuk metin dizileri (humor / teknik / ipucu kategorileri).
  global.VT_MASCOT_BUBBLES = {
    tr: {
      humor: [
        "Sifremi 'incorrect' yaptim; sistem beni duzeltiyor.",
        '2FA: guvenlik ve minik bir kalp carpintisi.',
        "Phishing maili 'acil' diyorsa ben de acil siliyorum.",
        'Think before you link, sonra click.',
        'Delete tusu bazen en iyi savunmadir.',
        'VPN acikken dijital pelerin aciliyor.',
        'USB bulup takmak korku filmi girisi gibi.',
        'Patch Tuesday kacarsa Risk Wednesday gelir.',
        'CAPTCHA ile insan oldugumu kanitliyorum.',
        'Public Wi-Fi bankacilik icin dogru sahne degil.',
        'Firewall da duygusal: bazen sadece no der.',
        'Loglar yalan soylemez, sadece ipucu saklar.',
        'Brute force sabirli ama adaletsizdir.',
        'Guncelleme sikicidir ama olay raporu daha sikicidir.',
        'Phishing mailleri gereksiz samimidir.',
        'Zero-day haberi = kahvede cift shot.',
        'MFA bir tik fazla, panik bir tik az.',
        'Yedekler felaket gununun emniyet kemeri.',
        'No patch, no peace.',
        'Siber hijyen, kriz yonetiminden ucuzdur.',
        'Parola yoneticisi kullanmak hafizaya iyilik.',
        'Sifre notunu monitore yapistirmak anti-pattern.',
        'Ayni sifreyi her yerde kullanmak speedrun modu.',
        'Kimlik avi maili konu satirindan belli olur.',
        'Acil yazan mail once suphe hak eder.',
        'Admin hakki kahve gibi: olcusu onemli.',
        'Unknown sender + attachment = guven test.',
        'Makine yavasladiysa malware de olabilir, sekme de 60 olabilir.',
        'Bir exploit haberi daha, bir kahve daha.',
        'Sistem aciliyor ama ben hala reboot bekliyorum.',
        'SOC nobetinde zaman dilimi yoktur.',
        'SIEM alarmi bazen pazar sabahi kadar sessizligi sever.',
        'False positive kalbe vurur, true positive geceye.',
        'Threat intel okumak dedektiflik gibidir.',
        'IOC listesi uzadikca moral kisalir.',
        'EDR sessizse ya her sey iyi ya da cok kotu.',
        'Least privilege: drama seviyesini dusurur.',
        'Klavye kisayolu guvenlikte de hayat kurtarir.',
        'Sifre degistirmek spor degil ama terletir.',
        'Backup test edilmediyse backup sayilmaz.',
        'Incident bridge acilinca kahve de acilir.',
        'Root cause bazen tek bir tik olur.',
        'Kilitlenen hesaplar brute force gunlugu gibidir.',
        'Ransomware demo istemez, canli yayin yapar.',
        'Kontrol listesi olmayan guvenlik yarimdir.',
        'Saldirgan tatil yapmaz, log da yapmaz.',
        'Threat hunting: samanlikta needle degil needle stack aramak.',
        'Sifre rotasyonu var ama akilda tutma yok.',
        'Guncel olmayan ajan, acik kapi gibidir.',
        'Guvenlikte kisa yol genelde uzun gece demektir.'
      ],
      technical: {
        soc: [
          'Event ID 4624: Basarili logon olayi.',
          'Event ID 4625: Basarisiz logon denemesi.',
          'Event ID 4648: Baska kimlik bilgisi ile logon denemesi.',
          'Event ID 4672: Ozel yetkiler atanan logon.',
          'Event ID 4688: Yeni process olusturuldu.',
          'Event ID 4697: Sisteme servis kuruldu.',
          'Event ID 4698: Scheduled task olusturuldu.',
          'Event ID 4702: Scheduled task guncellendi.',
          'Event ID 4720: Yeni kullanici hesabi olusturuldu.',
          'Event ID 4728: Kullanici privileged gruba eklendi.',
          'Event ID 4732: Local security-enabled gruba uye eklendi.',
          'Event ID 4740: Hesap lockout oldu.',
          'Event ID 1102: Security log temizlendi.'
        ],
        dfir: [
          'Komut: wevtutil qe Security /c:5 /rd:true -> son 5 Security eventi.',
          'Komut: tasklist /v -> process + kullanici + pencere bilgisi.',
          'Komut: taskkill /PID 1234 /F -> process sonlandirma.',
          'Komut: wmic process get name,processid,parentprocessid -> parent-child izi.',
          'Komut: net user -> lokal kullanici hesaplarini listeler.',
          'Komut: net localgroup administrators -> yerel admin uyeleri.',
          'Komut: schtasks /query /fo LIST /v -> scheduled task ayrintisi.',
          'Komut: driverquery -> yuklu suruculer listesi.',
          'Komut: reg query HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run -> autorun anahtarlari.',
          'Komut: certutil -hashfile dosya SHA256 -> hash uretir.',
          'Komut: powershell Get-FileHash dosya -Algorithm SHA256 -> hash dogrular.',
          'Komut: systeminfo -> host, patch, boot time bilgisi.',
          'Komut: quser -> aktif oturumlari gosterir.'
        ],
        blueTeam: [
          'Komut: netstat -ano -> acik portlar ve PID bilgisi.',
          'Komut: netstat -anob -> portu acan binary (admin gerekir).',
          'Komut: ipconfig /all -> ag adaptoru, DNS, DHCP ayrintisi.',
          'Komut: arp -a -> ARP cache goruntuler.',
          'Komut: route print -> routing tablosunu gosterir.',
          'Komut: whoami /groups -> token grup uyelikleri.',
          'Komut: whoami /priv -> token privilege listesi.',
          'Komut: nslookup domain.com -> DNS cozumleme kontrolu.',
          'Komut: ping hedef -> erisilebilirlik + RTT.',
          'Komut: tracert hedef -> hop bazli yol analizi.',
          'Komut: Test-NetConnection host -Port 443 -> port erisim testi (PowerShell).',
          'Komut: Get-Service | ? {$_.Status -eq "Running"} -> calisan servisler.'
        ],
        webSec: [
          'Komut: curl -I https://site.com -> sadece HTTP headerlari.',
          'Komut: curl -L URL -> redirect zincirini takip eder.',
          'Komut: curl -k URL -> TLS dogrulamasini atlar (test amacli).',
          'Komut: openssl s_client -connect host:443 -> TLS sertifika detayi.',
          'Komut: nslookup -type=txt domain.com -> SPF/DMARC gibi TXT kayitlari.',
          'Komut: dig +short domain.com A -> hizli DNS A kaydi (Unix).',
          'Komut: dig +short domain.com MX -> posta sunucusu kayitlari.',
          'Komut: curl -sI URL | findstr -i "security" -> security header kontrolu.',
          'Terim: HTTP 301/302 = yonlendirme cevabi.',
          'Terim: HTTP 401 = auth gerekli; 403 = yetki reddi.',
          'Terim: HTTP 429 = rate limit asimi.',
          'Terim: CSP header, tarayiciya hangi kaynaklara izin verilecegini soyler.'
        ]
      }
    },
    en: {
      humor: [
        "I set my password to 'incorrect' so I get corrected.",
        '2FA: extra security and extra taps.',
        "If an email says urgent, I start with delete.",
        'Think before you link.',
        'Delete is a valid phishing response.',
        'VPN on, anxiety down.',
        'Random USB drives are plot devices.',
        'No patch Tuesday means risky Wednesday.',
        'CAPTCHA keeps my ego in check.',
        'Public Wi-Fi is not your bank office.',
        'My firewall says no faster than I do.',
        'Logs do not lie; they just whisper.',
        'Brute force is patience with bad intent.',
        'Updates are boring until incident day.',
        'Phishing emails are always too friendly.',
        'Zero-day news pairs with strong coffee.',
        'MFA means one more tap, one less breach.',
        'Backups are seatbelts for bad days.',
        'No patch, no peace.',
        'Cyber hygiene is cheaper than IR.',
        'Password managers save memory and dignity.',
        'Sticky-note passwords are not encryption.',
        'Password reuse is a dangerous speedrun.',
        'Urgent subject lines deserve extra doubt.',
        'Unknown sender + attachment = pause.',
        'Admin rights are espresso: keep them small.',
        'Security popups always appear during demos.',
        'SOC night shift runs on alerts and caffeine.',
        'False positives are cardio for analysts.',
        'True positives ruin weekend plans.',
        'Threat intel is detective fiction with logs.',
        'IOC lists get longer, patience gets shorter.',
        'EDR silence can mean peace or trouble.',
        'Least privilege reduces drama.',
        'Security checklists prevent exciting outages.',
        'Root cause is often one tiny click.',
        'Locked accounts are brute-force breadcrumbs.',
        'Ransomware does not ask for calendar invites.',
        'No tested restore, no real backup.',
        'Patch notes are bedtime stories for blue teams.',
        'Every incident starts with one weird event.',
        'SIEM rules age like milk without tuning.',
        'Threat hunting is hide-and-seek with evidence.',
        'Security debt compounds fast.',
        'Cloud misconfigurations travel at light speed.',
        'One exposed bucket can ruin many mornings.',
        'Detection engineering is coding with paranoia.',
        'Good telemetry beats good guesses.',
        'An unlabeled alert is future confusion.',
        'Shortcuts in security become long nights.'
      ],
      technical: {
        soc: [
          'Event ID 4624: Successful logon.',
          'Event ID 4625: Failed logon attempt.',
          'Event ID 4648: Logon attempt using explicit credentials.',
          'Event ID 4672: Special privileges assigned to new logon.',
          'Event ID 4688: New process creation.',
          'Event ID 4697: A service was installed.',
          'Event ID 4698: A scheduled task was created.',
          'Event ID 4702: A scheduled task was updated.',
          'Event ID 4720: A user account was created.',
          'Event ID 4728: Member added to privileged global group.',
          'Event ID 4732: Member added to local security group.',
          'Event ID 4740: Account lockout.',
          'Event ID 1102: Audit log was cleared.'
        ],
        dfir: [
          'Command: wevtutil qe Security /c:5 /rd:true -> tail Security log entries.',
          'Command: tasklist /v -> running processes with verbose details.',
          'Command: taskkill /PID 1234 /F -> force-stop a process.',
          'Command: wmic process get name,processid,parentprocessid -> process lineage.',
          'Command: net user -> list local user accounts.',
          'Command: net localgroup administrators -> list local admins.',
          'Command: schtasks /query /fo LIST /v -> enumerate scheduled tasks.',
          'Command: driverquery -> list loaded drivers.',
          'Command: reg query HKCU\\...\\Run -> startup autoruns.',
          'Command: certutil -hashfile file SHA256 -> calculate file hash.',
          'Command: Get-FileHash file -Algorithm SHA256 -> PowerShell hash.',
          'Command: systeminfo -> host, patch, and boot-time data.',
          'Command: quser -> currently logged-on sessions.'
        ],
        blueTeam: [
          'Command: netstat -ano -> active sockets + owning PID.',
          'Command: netstat -anob -> socket + executable mapping (admin).',
          'Command: ipconfig /all -> full Windows network config.',
          'Command: arp -a -> inspect ARP cache.',
          'Command: route print -> view routing table.',
          'Command: whoami /groups -> token group memberships.',
          'Command: whoami /priv -> token privilege list.',
          'Command: nslookup domain.com -> DNS resolution lookup.',
          'Command: ping host -> reachability and latency check.',
          'Command: tracert host -> hop-by-hop network path.',
          'Command: Test-NetConnection host -Port 443 -> TCP reachability.',
          'Command: Get-Service | ? {$_.Status -eq "Running"} -> running services.'
        ],
        webSec: [
          'Command: curl -I https://site.com -> response headers only.',
          'Command: curl -L URL -> follow redirects.',
          'Command: curl -k URL -> skip TLS verification (testing only).',
          'Command: openssl s_client -connect host:443 -> TLS cert/session details.',
          'Command: nslookup -type=txt domain.com -> check TXT records.',
          'Command: dig +short domain.com A -> quick A record lookup (Unix).',
          'Command: dig +short domain.com MX -> quick MX record lookup.',
          'Command: curl -sI URL | findstr -i "security" -> security header check.',
          'Term: HTTP 301/302 means redirection response.',
          'Term: HTTP 401 needs auth; HTTP 403 denies authorization.',
          'Term: HTTP 429 indicates rate limiting.',
          'Term: CSP header defines allowed content sources in browser.'
        ]
      }
    }
  };
})(typeof self !== 'undefined' ? self : this);
